pragma Singleton

import Quickshell

Singleton {
    property string primary: "#97ccf8"
    property string primaryFixed: "#cbe6ff"
    property string primaryFixedDim: "#97ccf8"
    property string on_primary: "#00344f"
    property string on_primaryFixed: "#001e30"
    property string on_primaryFixedVariant: "#004b71"
    property string primaryContainer: "#004b71"
    property string on_primaryContainer: "#cbe6ff"
    property string secondary: "#b8c8d9"
    property string secondaryFixed: "#d3e4f6"
    property string secondaryFixedDim: "#b8c8d9"
    property string on_secondary: "#22323f"
    property string on_secondaryFixed: "#0c1d29"
    property string on_secondaryFixedVariant: "#394956"
    property string secondaryContainer: "#394956"
    property string on_secondaryContainer: "#d3e4f6"
    property string tertiary: "#d0c0e8"
    property string tertiaryFixed: "#ebdcff"
    property string tertiaryFixedDim: "#d0c0e8"
    property string on_tertiary: "#362b4a"
    property string on_tertiaryFixed: "#211634"
    property string on_tertiaryFixedVariant: "#4d4162"
    property string tertiaryContainer: "#4d4162"
    property string on_tertiaryContainer: "#ebdcff"
    property string error: "#ffb4ab"
    property string on_error: "#690005"
    property string errorContainer: "#93000a"
    property string on_errorContainer: "#ffdad6"
    property string surface: "#101417"
    property string on_surface: "#e0e3e8"
    property string on_surfaceVariant: "#c1c7ce"
    property string outline: "#8b9198"
    property string outlineVariant: "#41474d"
    property string shadow: "#000000"
    property string scrim: "#000000"
    property string inverseSurface: "#e0e3e8"
    property string inverse_on_surface: "#2d3135"
    property string inversePrimary: "#29638a"
    property string surfaceDim: "#101417"
    property string surfaceBright: "#363a3e"
    property string surfaceContainerLowest: "#0b0f12"
    property string surfaceContainerLow: "#181c20"
    property string surfaceContainer: "#1c2024"
    property string surfaceContainerHigh: "#262a2e"
    property string surfaceContainerHighest: "#313539"
}
